#include "string"
#include "stdio.h"
#include "cstring"
#include "stdlib.h"
#include "iostream"
#include "sstream"
#include "vector"
#include "memory"
#include "stdexcept"
#include "array"
#include "cstdio"
#include <unistd.h>
#include <curl/curl.h>